export default {
  preface: [
    "À l'opposé,",
    "En premier lieu,",
    "Conséquemment,",
    "Néanmoins,",
    "Signalons aussi que",
    "À cet égard,",
    "Par ailleurs,",
    "Il résulte que",
    "N'oublions pas que",
    "Toutefois,",
    "En outre,",
    "En somme,",
    "Hélas,",
    "Plusieurs importants penseurs dans mon entourage, dont certains ont grandi parmi #groupe#, s'inquiètent que",
    "Plusieurs importants penseurs me rapportent que",
  ],

  // Tricherie: Augmenter les chances d'une formule
  // particulière en la dédoublant
  sujet: [
    "#groupe#",
    "#groupe#",
    "#groupe#",
    "#groupe#",
    "#groupe#",
    "#groupe#",
    "#groupe#, aidés par #groupe#,",
    "#groupe# et #groupe#",
    "#groupe#, donc #groupe#,",
    "#groupe#, c'est à dire #groupe#, #groupe#,",
  ],

  groupe: [
    "les féministes",
    "les anglophones",
    "les défavorisés",
    "les artistes",
    "les transgenres",
    "les immigrants",
    "les milléniaux",
    "les justiciers sociaux",
    "les assistés sociaux",
    "les musulmans",
    "les femmes biologiques",
    "les infortunés",
    "les plébiens",
    "les prolétaires",
    "les paysans",
    "les homosexuels",
    "les masses laborieuses",
    "les étudiants",
    "les syndicalistes",
    "les activistes",
    "les non-genrés",
    "ceux qui rejettent nos valeurs traditionnelles",
    "les apôtres de la rectitude politique",
    "les familles soi-disant intégrées",
    "les apôtres du wokisme",
    "ceux qui se proclâment ouverts d'esprit",
  ],

  mechancete: [
    "persécutent #ami#",
    "menacent #ami#",
    "assaillent #ami#",
    "s'acharnent sur #ami#",
    "dénigrent #ami#",
    "inquiètent #ami#",
    "déprécient #ami#",
    "harcèlent #ami#",
    "méconnaissent #ami#",
    "s'acharnent contre #ami#",
    "offensent #ami#",
    "alarment #ami#",
    "troublent #ami#",
    "pourfendent #ami#",
    "frustrent #ami#",
    "agressent #ami#",
    "calomnient #ami#",
    "embarassent #ami#",
    "tourmentent #ami#",
    "protestent #ami#",
    "souillent #ami#",
    "médisent #ami#",
    "déblatèrent leurs ragots dans les rues",
    "poursuivent leurs ignominies",
    "s'indiffèrent du bonapartisme",
    "négligent l'Église en ce siècle saint",
    "diluent la culture existante",
    "poussent un agenda woke",
  ],

  commiseration: [
    "commisèrent avec #mechant#",
    "attisent une ferveur indomptable chez #mechant#",
    "appuient ouvertement #mechant#",
    "supportent sans retenue #mechant#",
    "entretiennent leur compassion pour #mechant#",
    "cautionnent #mechant#",
  ],

  ami: [
    "la monarchie",
    "l'élite intellectuelle",
    "le municipalisme",
    "la jurisdiction",
    "leurs contemporains",
    "le corps ecclésiastique",
    "les infrastructures",
    "l'appareil gouvernemental",
    "la Première dame",
    "Sa Gracieuse Majesté",
    "les souverains",
    "le clergé",
    "le très cher Pape",
    "le sacerdoce",
    "mes collègues",
    "le patriarcat",
    "la vénérable Reine",
    "le Québécois moyen",
    "la paroisse",
    "l'ordre établi",
    "l'aristocratie en place",
    "les défenseurs de la démocratie",
    "le couple traditionnel",
  ],

  mechant: ["#groupe#"],

  scenario: [
    // Tricherie: Augmenter les chances d'une formule
    // particulière en la dédoublant
    "#preface# #sujet# #mechancete#.",
    "#preface# #sujet# #mechancete#.",
    "#preface# #sujet# #commiseration#.",
  ],

  origin: "#scenario#",
};
